---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: vendor/bundle
          BUNDLE_WITHOUT: "local"
    steps:
      - checkout

      - restore_cache:
          keys:
            - gladwords-bundle-v2-{{ checksum "Gemfile.lock" }}
            - gladwords-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: gladwords-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --format documentation
